### ISSUE TITLE
C2-W4: back_prop & gradient_descent

### ISSUE THREAD

**Issue by shiinalight** [FahdSeddik/DeepLearning.AI-Natural-Language-Processing-Specialization#1]
Hello; I was trying to learn this course and I ended up stuck in back prop and gradient descent, and  I came a cross your profile and tried to use your solution, although I get more tests passed, but still stuck.
would be kind to take a look at the outputs I got for these two exercises and help me to spot the problem?
Best 
Nooshin

[C2_W4_Assignment.pdf](https://github.com/FahdSeddik/DeepLearning.AI-Natural-Language-Processing-Specialization/files/12445437/C2_W4_Assignment.pdf)

**Comment by FahdSeddik** [comment]
I believe the problem is coming from implementing ReLU. As you can see in the screenshot below the output vectors have negative values replaced with zero compared to the expected.
![image](https://github.com/FahdSeddik/DeepLearning.AI-Natural-Language-Processing-Specialization/assets/62207434/a715db46-4a31-4b40-8c3e-35fee6e9ee8a)  

I believe this is a result of the following line, hope that helps.
![image](https://github.com/FahdSeddik/DeepLearning.AI-Natural-Language-Processing-Specialization/assets/62207434/7f456153-deb7-4604-b336-7681473f3ddb)

**Comment by shiinalight** [comment]
Perfect! it worked
thanks a lot
